### ISSUE TITLE
Issue: `key` prop should be allowed

### ISSUE THREAD

**Issue by lanesawyer** [isographlabs/isograph#111]
# Issue: `key` prop should be allowed 

I got the pet demo up and running and noticed the console is throwing an error due to a component in a list not having a `key`.

I found the following in the demo code:
```ts
// the key is not needed here!
// eslint-disable-next-line react/jsx-key
<pet.PetSummaryCard />
```

And adding `key={pet.id}` got the error in the console to go away at runtime. But then I got the following TypeScript error:
```ts
Type '{ key: string; }' is not assignable to type 'Record<string, never>'.
  Property 'key' is incompatible with index signature.
    Type 'string' is not assignable to type 'never'.ts(2322)
```

I think that the `__output_type`s should include an optional `key` prop when using React and Typescript so that it can be added when the components are in a loop.

**Comment by rbalicki2** [comment]
Yes. This is a sore point. This is harder than it sounds though 😭 

* Right now, the generated type for the props is `Record<string, never>`, which is a way of enforcing that you pass no additional props.
* If we change that to `{ key: string }` (and maybe ref? Who knows), TypeScript's lack of exact object types (which exist in [flow](https://flow.org/en/docs/types/objects/)), then one can pass whatever props you want to these components, and TypeScript will not complain. (At least, if it goes through another variable)
* AFAICT, TypeScript does not expose the `IntrinsicProps` (or whatever they're called) (i.e. key, maybe ref) that are allowed on all components. But maybe we can use some advanced TypeScript-fu to get at them.
* We usually should not need the `key`, though, because each component is unique. (See `componentCache.ts`. The first step is to look up the component by ID. So the `PetSummaryCard` for a pet with id 0 is not the same as the one with id 1)
* I say usually, because if the list contains multiple pets with the same ID (and which is clearly allowed by GraphQL), we can render the same component multiple times in the list. (But then what would you use as a key? Who knows!)

**Comment by rbalicki2** [comment]
The thing is, if you have a single prop, TypeScript nonetheless lets you pass additional props, so maybe my objection is silly. I'm open to that as well

**Comment by PatrykWalach** [comment]
`{}` should be fine, because defined props get merged with, `IntrinsicAttributes`, and `IntrinsicAttributes` contains `key`. As long as type has at least one key, typescript won't allow extra attributes directly. [Playground Link](https://www.typescriptlang.org/play/?#code/JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChTMBXAOw2AmrgEEwwAKMHMAZwC44A3gF8AlANJxJcIjEpRG1SgBslpIeQA8LMHEwQIAXgBERuAHoAfOW1txU3fv74yooA)

>AFAICT, TypeScript does not expose the IntrinsicProps (or whatever they're called) (i.e. key, maybe ref) that are allowed on all components. But maybe we can use some advanced TypeScript-fu to get at them.


It's `JSX.IntrinsicAttributes`

>I say usually, because if the list contains multiple pets with the same ID (and which is clearly allowed by GraphQL), we can render the same component multiple times in the list. (But then what would you use as a key? Who knows!)

Ideally we would have an `Edge` with `cursor`

**Comment by PatrykWalach** [comment]
And setting `JSX.IntrinsicAttributes` as default would mean someone might try to access `key` and will get a runtime error
```tsx
function App({ key }: JSX.IntrinsicAttributes){
  return null
}
```
