### ISSUE TITLE
[typescript] Turn on all of the recommended config options

### ISSUE THREAD

**Issue by rbalicki2** [isographlabs/isograph#213]
* The stricter the better

**Comment by lanesawyer** [comment]
I could take a look at this soon. What do you think about applying all of the TS config options marked as "recommended"? I'm not sure how many items there would be to fix with that turned on, but I could take a look at that while I'm in there.

**Comment by rbalicki2** [comment]
Hell yeah! Yes, 100%, the stricter the TS, the better. I'll modify the task to turn on all the recommended items.

Feel free to fix the ones that are obvious (ideally in separate PRs that land before we turn on the rule), but also feel free to just ts-expect-error anything that isn't obvious. Or we can touch base and figure out how to change the code to turn on the various rules.

**Comment by lanesawyer** [comment]
I've got a PR to turn on the recommended settings. There was only one to add, and no violations in the codebase 😁

I'll do a separate PR for `noUncheckedIndexAccess`, as that will require some code changes. It's not one of the recommended settings, but the original intent of this issue was to turn that on, so I'll try to get to that this week.
